apiVersion: fluxcd.io/v2beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  targetNamespace: istio-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./istio
